### ISSUE TITLE
Treasury | Europa v0.2 | Intake review | Nice to have request, Improvement in Contract Trap error message

### ISSUE THREAD

**Issue by rajesh-nodle** [patractlabs/europa#62]
Request to improve the verbose in contract Trap error message, some thing like
"This Trap X is due to this Y". Discussed with Patract team, looks like 
this feature has dependency on "wasm executor", and team has plan to add this in future milestones.

![](https://i.imgur.com/CTa19PS.png)

**Comment by atenjin** [comment]
This has a lot of work to do... v0.3 does not include this, but I believe this work could be improved in future.

**Comment by atenjin** [comment]
for now, the trap reason can be printed by ink! handle_panic function, thus, I think europa do not need to design special feature to print it.
