### ISSUE TITLE
getFinalizedHead() always returns 0 block Hash

### ISSUE THREAD

**Issue by azhu003** [patractlabs/europa#67]
call: ``api.rpc.chain.getFinalizedHead()``
version: ``version 0.2.1-9dcdb46-x86_64-macos``

**Comment by atenjin** [comment]
europa does not have the concept of finalize, thus there is no finalize for europa.
remember europa is a sendbox, it just provides the mock node layer, sandbox for runtime and the runtime environment for wasm contract, it does not provide the consensus system.
